# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grapevine-130' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grapevine
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  
  pod 'GoogleUtilities'

  pod 'SnapSDK', '1.4.0', :subspecs => ['SCSDKCreativeKit']

end
