# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grapevine-130' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grapevine
  # add the Firebase pod for Google Analytics
  pod 'GoogleUtilities'

  pod 'SnapSDK', '1.4.0', :subspecs => ['SCSDKCreativeKit']

  pod 'MaterialComponents/BottomNavigation'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Buttons+Theming'
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/Cards'

end
